name: Sphinx

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/**'

jobs:
  build-html:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pacman-key --init && pacman -Syu git"
        build-command: "sphinx-build -b html . build"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ARU-${{ github.sha }}
        path: docs/build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/
        keep_files: true
  build-pdf:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - uses: actions/checkout@v2
    - name: Build PDF
      run: |
         pacman-key --init
         pacman -Syu --noconfirm
         pacman -S --noconfirm texlive-latexextra texlive-fontsextra git texlive-core python-sphinx ttf-dejavu
         cd docs
         make latexpdf
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ARU-${{ github.sha }}
        path: docs/build/latex/ARU.pdf
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/
        keep_files: true
